### PR TITLE
Add generate block command

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Comment by andrewtoth** [comment]
This RPC takes both`Txid`s and `RawTx`s. We should support both I think. Perhaps by making it take a new enum that is either a `RawTx` or `Txid`?

**Comment by andrewtoth** [comment]
Also dupe of https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/189. Not sure if that author is still active though.

**Comment by benthecarman** [comment]
> This RPC takes bothTxids and RawTxs. We should support both I think. Perhaps by making it take a new enum that is either a RawTx or Txid?

done

File: integration_test/src/main.rs [hunk 1]
```diff
@@ -277,6 +278,55 @@ fn test_get_balances_generate_to_address(cl: &Client) {
...
+        vout: unspent.vout,
+        script_pub_key: unspent.script_pub_key,
+        redeem_script: None,
+        amount: Some(unspent.amount),
+    };
+    let res = cl.sign_raw_transaction_with_wallet(&tx, Some(&[input]), None).unwrap();
+    assert!(res.complete);
+
+    let raw_tx = bitcoincore_rpc::MineableTx::RawTx(res.transaction().unwrap());
+    let result = cl.generate_block(&cl.get_new_address(None, None).unwrap(), &[raw_tx]).unwrap();
```
Comment (andrewtoth) [inline integration_test/src/main.rs:325]: Should we also put a tx in the mempool and use its txid here to test both cases of the enum?

Otherwise ACK.

**Review by andrewtoth — APPROVED** [review]

File: integration_test/src/main.rs (hunk 1 above)
Comment (benthecarman) [reply integration_test/src/main.rs:326]: done

**Comment by apoelstra** [comment]
Thanks @benthecarman! concept ACK from me. I have a mild preference that the enum have a more generateblock-specific name but I can't think of a good one.

Heads up that this does not compile on Rust 1.41, which is our MSRV. I've approved CI so you should see a failure soon but here is the error on my end:
```
error[E0277]: the trait bound `bitcoin::blockdata::transaction::Transaction: bitcoincore_rpc::client::RawTx` is not satisfied
   --> integration_test/src/main.rs:376:29
    |
376 |     cl.send_raw_transaction(tx).unwrap();
    |                             ^^ the trait `bitcoincore_rpc::client::RawTx` is not implemented for `bitcoin::blockdata::transaction::Transaction`
    |
    = help: the following implementations were found:
              <&'a bitcoin::blockdata::transaction::Transaction as bitcoincore_rpc::client::RawTx>

error: aborting due to previous error
```

File: client/src/client.rs [hunk 2]
```diff
@@ -186,6 +186,13 @@ impl RawTx for String {
     }
 }
 
+/// The different authentication methods for the client.
+#[derive(Clone, Debug, Hash, Eq, PartialEq, Ord, PartialOrd)]
+pub enum MineableTx {
+    RawTx(Transaction),
```
Comment (andrewtoth) [inline client/src/client.rs:192]: Actually this doesn't have to be a `Transaction` but a `RawTx` trait object.

Comment (benthecarman) [reply client/src/client.rs:192]: This doesn't really work, have to make it a `Box<dyn RawTx>` but still run into errors with sizing

Comment (andrewtoth) [reply client/src/client.rs:192]: Right, it would actually have to be a generic enum.

Comment (andrewtoth) [reply client/src/client.rs:192]: Hmm actually maybe not...

**Comment by apoelstra** [comment]
@benthecarman compilation is fixed, but I believe now this is going to fail because `cargo fmt` doesn't pass :)

**Comment by benthecarman** [comment]
> @benthecarman compilation is fixed, but I believe now this is going to fail because cargo fmt doesn't pass :)

Ah yeah there we're some unrelated to my changes so I didn't fix

**Review by apoelstra — APPROVED** [review]
ACK badf7fcc8a7d996b7465c231350dbe040a201743

**Comment by apoelstra** [comment]
What version of core was this introduced in? It looks like it's not present in 0.19 and 0.20, which we run integration tests against.

I'm not sure how we handle feature-gating new RPCs here. It's not really my crate..

**Comment by andrewtoth** [comment]
Version 0.21

**Comment by tcharding** [comment]
Do you have clock cycles for this PR @benthecarman? Otherwise I can pick it up, if I do it it will not get done till after next release.

FTR I'm attempting to do a quick-ish release then start working on the harder stuff (update crate to support latest Core version).

**Comment by benthecarman** [comment]
I am at bitcoin++ this week, if you want a fast release go ahead and take this over

**Comment by tcharding** [comment]
Ha! 'quick-ish release' I must have been on crack when I wrote that.
